name: blurrycontainer
description: Container with Frosty Glass effect.
version: 1.0.0
homepage: https://github.com/ranjeetrocky/blurry_container

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0