name: blurrycontainer
description: "Make lovely Container with Frosty Glass effect where you can control blur, height, width, color, elevation, padding, borderRadius etc."
version: 2.0.1+1
homepage: https://github.com/kishan-dhankecha/blurrycontainer

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter: { sdk: flutter }

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test: { sdk: flutter }
